# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eschool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Continuous_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('Total_Mark', models.IntegerField(null=True)),
                ('comment', models.TextField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(default='simplicio', max_length=200)),
                ('surname', models.CharField(default='sithole', max_length=40)),
                ('Test_name', models.CharField(max_length=50)),
                ('Test_mark', models.IntegerField(null=True)),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
