# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuous_assessment',
            name='Total_Mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='continuous_assessment',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
