# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continuous', '0002_auto_20170908_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuous_assessment',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eschool.Student'),
        ),
    ]
