# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschool', '0002_auto_20170903_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Physical_Address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='Physical_Address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Physical_Address',
            field=models.TextField(max_length=200),
        ),
    ]
