# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschool', '0003_auto_20170903_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student_number',
        ),
        migrations.AddField(
            model_name='parent',
            name='student_number',
            field=models.ManyToManyField(to='eschool.Student'),
        ),
    ]
