# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eschool', '0004_auto_20170903_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='student_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='Student_number',
            field=models.CharField(max_length=50),
        ),
    ]
