# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 8)),
        ),
    ]
