# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170908_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 10)),
        ),
    ]
