# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20180212_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2018, 2, 13)),
        ),
    ]
